permissions:
  - 'join group'
  - 'view group_node:event content'
  - 'view group_node:event entity'
  - 'view group_node:topic content'
  - 'view group_node:topic entity'
  - 'view group'
  - 'access posts in group'
  - 'update own group_node:topic entity'
  - 'update own group_node:event entity'
  - 'access comments'
  - 'view group_membership content'
  - 'view stream page group'
