dependencies:
  config:
    1: group.type.course_advanced
    2: group.type.course_basic
display:
  default:
    display_options:
      filters:
        type:
          admin_panel: ''
          entity_field: type
          group_type: group
          expose:
            description: ''
            identifier: ''
            label: ''
            multiple: false
            operator: ''
            operator_id: ''
            reduce: ''
            remember: false
            remember_roles:
              authenticated: authenticated
            required: false
            use_operator: false
          exposed: false
          field: type
          group: 2
          group_info:
            default_group: All
            description: ''
            identifier: ''
            label: ''
            multiple: false
            optional: true
            remember: false
            widget: select
          group_type: group
          id: type
          is_grouped: false
          operator: 'not in'
          plugin_id: bundle
          relationship: none
          table: groups_field_data
          value:
            course_advanced: course_advanced
            course_basic: course_basic
