display:
  default:
    display_options:
      arguments:
        gid:
          specify_validation: true
          validate:
            type: entity:group
          validate_options:
            access: ''
            bundles:
              course_advanced: course_advanced
              open_group: open_group
              public_group: public_group
              closed_group: closed_group
            multiple: false
            operation: view
      filters:
        type:
          value:
            open_group-group_membership: open_group-group_membership
            public_group-group_membership: public_group-group_membership
            closed_group-group_membership: closed_group-group_membership
            course_advanced-group_membership: course_advanced-group_membership
