display:
  default:
    display_options:
      filters:
        type:
          id: type
          table: groups_field_data
          field: type
          relationship: none
          group_type: group
          admin_label: ''
          operator: 'not in'
          value:
            course_advanced: course_advanced
            course_basic: course_basic
          group: 1
          exposed: false
          expose:
            operator_id: ''
            label: ''
            description: ''
            use_operator: false
            operator: ''
            identifier: ''
            required: false
            remember: false
            multiple: false
            remember_roles:
              authenticated: authenticated
            reduce: false
          is_grouped: false
          group_info:
            label: ''
            description: ''
            identifier: ''
            optional: true
            widget: select
            multiple: false
            remember: false
            default_group: All
            default_group_multiple: {  }
            group_items: {  }
          entity_type: group
          entity_field: type
          plugin_id: bundle
