display:
  default:
    display_options:
      arguments:
        gid:
          specify_validation: true
          validate:
            type: entity:group
          validate_options:
            access: ''
            bundles:
              course_advanced: course_advanced
              open_group: open_group
              closed_group: closed_group
            multiple: false
            operation: view
      filters:
        type:
          value:
            open_group-group_node-event: open_group-group_node-event
            closed_group-group_node-event: closed_group-group_node-event
            course_advanced-group_node-event: course_advanced-group_node-event
